### ISSUE TITLE
relate paper

### ISSUE THREAD

**Issue by chengwei0427** [zhouruihao1001/NDD#1]
Hi, @zhouruihao1001 
Congratulation, and can you upload the relate paper.

**Comment by zhouruihao1001** [comment]
Thanks. We will upload the paper soon.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Aug 8, 2022 03:24 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;[zhouruihao1001/NDD] relate paper (Issue #1)

&nbsp;




Hi, @zhouruihao1001
 Congratulation, and can you upload the relate paper.

**Comment by chengwei0427** [comment]
Any new progress?

**Comment by chengwei0427** [comment]
Hi, @zhouruihao1001 
   Maybe you can upload the paper to the git project?
