### ISSUE TITLE
关于KITTI测试过程中的真值设定问题。

### ISSUE THREAD

**Issue by SlamCabbage** [zhouruihao1001/NDD#6]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/95751923/229411942-3a12c932-28bc-4c99-9e15-4843da3cf8de.png">
您好，我尝试采用您的实验设置进行对比，但是在这个过程中，我想了解一下是如何选择KITTI数据的真值的呢？是query其位姿一定距离范围内是否有candidates作为真值判断的标准吗？在查找回环的时候，是否也是能找到这个范围内的某一个candidate即作为true？

**Comment by zhouruihao1001** [comment]
﻿If a ground truth pose distance between the query and the matched node is less than 5m, the detection is consider as a true positive. In total 50 adjacent nodes are excluded from the search.
----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Adam&nbsp;Liao ***@***.***&gt;;
发送时间：2023年4月3日(星期一) 中午12:35
收件人："zhouruihao1001/NDD" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[zhouruihao1001/NDD] 关于KITTI测试过程中的真值设定问题。 (Issue #6)
-----------------------------------

 

 

 您好，我尝试采用您的实验设置进行对比，但是在这个过程中，我想了解一下是如何选择KITTI数据的真值的呢？是query其位姿一定距离范围内是否有candidates作为真值判断的标准吗？在查找回环的时候，是否也是能找到这个范围内的某一个candidate即作为true？

**Comment by SlamCabbage** [comment]
One more question: Is there timing information in the process of generating the ground truth? For example, when 1000-th frame is used as a query, whether the experiment can find the frames after it.

**Comment by zhouruihao1001** [comment]
No, only use point clouds as input for retrieval and matching experiments. The loop closure is determined whether a robot has returned to the previously visited scence.
