### ISSUE TITLE
questions about ground truth

### ISSUE THREAD

**Issue by SlamCabbage** [zhouruihao1001/NDD#7]
I generated the loop closure detection ground truth of KITTI according to the requirement "If a ground truth pose distance between the query and the matched node is less than 5m, the detection is considered as a true positive. In total 50 adjacent nodes are excluded from the search." in the paper, but there are some deviations from those listed in TABLE I THE DETAILS OF SELECTED DATASETS LISTS in the paper.

sequence   your   mine
00 852 / 4541 805 / 4541
02 309 / 4661 309/4661
05 493 / 2761 504 / 2761
06 153/1101 270/1101
08 332/4072 320/4072

**Comment by SlamCabbage** [comment]
Can you provide your ground truth data? Or more detailed truth generation rules?

**Comment by zhouruihao1001** [comment]
Your ground truth data is correct. We simply&nbsp;copy the number of nodes from the scan context in our paper.

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Adam&nbsp;Liao ***@***.***&gt;;
发送时间：2023年4月11日(星期二) 晚上9:30
收件人："zhouruihao1001/NDD" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [zhouruihao1001/NDD] questions about ground truth (Issue #7)
-----------------------------------

 

 
Can you provide your ground truth data? Or more detailed truth generation rules?

**Comment by SlamCabbage** [comment]
Okay, I understand that the ground truth in SC is within 4m, and in your paper it is within 5m. May I ask whether the methods compared in your paper are tested according to 5m?

**Comment by zhouruihao1001** [comment]
Yes, our paper are tested according to 5m. Thanks for your feedback.

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Adam&nbsp;Liao ***@***.***&gt;;
发送时间：2023年4月11日(星期二) 晚上9:44
收件人："zhouruihao1001/NDD" ***@***.***&gt;;
抄送："周瑞浩 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [zhouruihao1001/NDD] questions about ground truth (Issue #7)
-----------------------------------

 

 
Okay, I understand that the ground truth in SC is within 4m, and in your paper it is within 5m. May I ask whether the methods compared in your paper are tested according to 5m?

**Comment by SlamCabbage** [comment]
There is no PR curve of kitti07 in this article, can you provide the drawing data of KITTI curve? I intend to add the results of my method on top of the results of the methods compared in your article. I would be very grateful if I could!

**Comment by zhouruihao1001** [comment]
[07.pdf](https://github.com/zhouruihao1001/NDD/files/11201421/07.pdf)

**Comment by SlamCabbage** [comment]
Very grateful for your help！
